### ISSUE TITLE
Build Error with no package.cfg file

### ISSUE THREAD

**Issue by JunhoSuh** [Broadcom-Switch/SAI#1]
Hi,

I am trying to build SAI with OpenNSL SDK for Dell switch, but there is no package.cfg file for build. Error message is as follow:
Makefile:19: package.cfg: No such file or directory

How can I solve this problem?

Thanks~

**Comment by simonknee** [comment]
The package.cfg was missing, now resolved.  There were also some issues with the Makefile, now fixed, and we updated the build notes in README.md.  Could you give it another try?
