### ISSUE TITLE
Port breakout with BCM56960 Tomahawk

### ISSUE THREAD

**Issue by byronyi** [Broadcom-Switch/SAI#10]
I consulted SONiC if Tomahawk supports 2x50G or 4x25G breakout, and their answer is no as BRCM SAI does not support it. See [here](https://www.google.com/url?q=https%3A%2F%2Fna01.safelinks.protection.outlook.com%2F%3Furl%3Dhttps%253A%252F%252Fgroups.google.com%252Fd%252Fmsgid%252Fsonicproject%252Fe85c2454-3643-4f93-8301-6047311285e5%252540googlegroups.com%253Futm_medium%253Demail%2526utm_source%253Dfooter%26data%3D02%257C01%257Cgulv%2540microsoft.com%257C968ea3a348b64fb8a25d08d55cbc7557%257C72f988bf86f141af91ab2d7cd011db47%257C1%257C1%257C636516886864068488%26sdata%3DrVEqZjPqmxq3BI%252FJ3ppM1hgyoMEI0HNENUn6L48Hkh8%253D%26reserved%3D0&sa=D&sntz=1&usg=AFQjCNGzDA_BfxHqkfg4csoaWu1-H7W10g).

When will that feature be supported?

**Comment by florath** [comment]
Does anybody know if this is still is not supported in 2022?
